-- MySQL Script generated by MySQL Workbench
-- ven. 27 oct. 2017 11:18:33 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema doURBEX
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema doURBEX
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `doURBEX` DEFAULT CHARACTER SET utf8 ;
USE `doURBEX` ;

-- -----------------------------------------------------
-- Table `doURBEX`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doURBEX`.`User` (
  `user_login` VARCHAR(45) NOT NULL,
  `user_mdp` VARCHAR(45) NOT NULL,
  `user_img` VARCHAR(45) NULL,
  `user_firstname` VARCHAR(45) NULL,
  `user_lastname` VARCHAR(45) NULL,
  `user_yearsold` INT NULL,
  PRIMARY KEY (`user_login`),
  UNIQUE INDEX `user_login_UNIQUE` (`user_login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doURBEX`.`Place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doURBEX`.`Place` (
  `place_id` INT NOT NULL AUTO_INCREMENT,
  `place_name` VARCHAR(45) NOT NULL,
  `place_img` VARCHAR(45) NULL,
  `place_desc` TEXT NULL,
  `place_posX` FLOAT NOT NULL,
  `place_posY` FLOAT NOT NULL,
  `place_addedByUser` VARCHAR(45) NULL,
  PRIMARY KEY (`place_id`),
  INDEX `fk_Place_User_idx` (`place_addedByUser` ASC),
  CONSTRAINT `fk_Place_User`
    FOREIGN KEY (`place_addedByUser`)
    REFERENCES `doURBEX`.`User` (`user_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doURBEX`.`Rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doURBEX`.`Rate` (
  `rate_id` INT NOT NULL AUTO_INCREMENT,
  `rate_value` INT NOT NULL,
  `User_user_login` VARCHAR(45) NOT NULL,
  `Place_place_id` INT NOT NULL,
  PRIMARY KEY (`rate_id`, `User_user_login`, `Place_place_id`),
  INDEX `fk_Rate_User1_idx` (`User_user_login` ASC),
  INDEX `fk_Rate_Place1_idx` (`Place_place_id` ASC),
  CONSTRAINT `fk_Rate_User1`
    FOREIGN KEY (`User_user_login`)
    REFERENCES `doURBEX`.`User` (`user_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rate_Place1`
    FOREIGN KEY (`Place_place_id`)
    REFERENCES `doURBEX`.`Place` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doURBEX`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doURBEX`.`Comment` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `comment_content` TEXT NOT NULL,
  `User_user_login` VARCHAR(45) NOT NULL,
  `Place_place_id` INT NOT NULL,
  PRIMARY KEY (`comment_id`, `User_user_login`, `Place_place_id`),
  INDEX `fk_Comment_User1_idx` (`User_user_login` ASC),
  INDEX `fk_Comment_Place1_idx` (`Place_place_id` ASC),
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`User_user_login`)
    REFERENCES `doURBEX`.`User` (`user_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Place1`
    FOREIGN KEY (`Place_place_id`)
    REFERENCES `doURBEX`.`Place` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
